### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by glyph** [glyph/Pomodouroboros#22]
like literally any automated testing configuration at all (github actions, probably)

**Comment by benchatt** [comment]
Got started on this with this PR: https://github.com/glyph/Pomodouroboros/pull/54 -- lots of room to expand this too (including running the non-GUI unit tests here, adding linting and formatting if desired)

**Comment by glyph** [comment]
Thanks @benchatt !

**Comment by glyph** [comment]
I'm going to call this "done", since this was just the ticket for bootstrapping. More tests will need to come later, of course.
